### ISSUE TITLE
Jio TV not working from yesterday night

### ISSUE THREAD

**Issue by Jkadam30** [botallen/repository.botallen#241]
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

**Comment by saumilwaghela** [comment]
TRIED kodi 19.3, Yesterday updated version jio tv 2.2.2, tried vpn also... fails

**Comment by sonulohani** [comment]
Yeah jio tv is not working

**Comment by 0harshkumar0** [comment]
bro just reinstaal jio tv addon and login again and setup then u good to go

**Comment by 0harshkumar0** [comment]
> Yeah jio tv is not working

bro just reinstaal jio tv addon and login again and setup then u good to go

**Comment by 0harshkumar0** [comment]
> I did that, reinstalled kodi 19.3 but still not working

try more one time bcz mine  also started 1 hr ago i reinstalled

**Comment by saumilwaghela** [comment]
got it fixed by following below step
Since URL was working fine I needed no vpn case may different for other
Before starting ensure that you have updated your official jio tv app and have logged in with your sim on your phone
Now in your tv, follow steps and install this repo. Do login and try once to start channel
If doesn't then follow below....
Goto add on-- pvr client--- download IPTV simple client and once installation done goto add on jiotv long press on it goto Setup and choose simple IPTV option. It will ask you to restart kodi... Exit the app from power button on top left and sometimes it hangs wait for 20 sec if it doesn't go then kill the app...
Open and test
It worked for my case

**Comment by Jkadam30** [comment]
Its working now. Thank you

**Comment by jhasunilvats** [comment]
JioTV channels not launcing since 11.01.2023 in kodi 19.3 
Uninstalled and installed many times still issue persists
Requested for resolution, Pl
Thank You
