### ISSUE TITLE
Playback Failed. One or more items failed to play

### ISSUE THREAD

**Issue by Nzzyme** [botallen/repository.botallen#291]
**Your Environment**
- Add-on name: Jiotv
- Add-on version: 2.0.0
- Kodi version: Kodi 19.3
- Operating system version/name: Android 8.1 (Android TV Box)
- Using from country: India 

**Describe the bug**
Since yesterday, I am getting the following error when playing most of the channels (see screenshot).

Some channels play and some don't giving this error. Ex: IndiaTV, Aaj Tak, Discovery Science. These channels show the error.

**To Reproduce**
Play any of the above mentioned channels.

**Expected behavior**
Supposed to play without an error

**Screenshots**

![IMG_20220813_153903](https://user-images.githubusercontent.com/6959116/184479421-dcc0a7b1-fc36-41f5-88b0-1642b0f98428.jpg)

**Additional context**
The above mentioned channels play well on the official JioTV android app.
Tried to clear cache in Add-on settings
Tried to logout and relogin

**Debug log**
Sorry, I can't do this at the moment.

**Comment by Nzzyme** [comment]
Seems fixed now.

**Comment by vin2015** [comment]
No not yet fixed, still giving the above issues for majority of the channels

**Comment by Hishantik** [comment]
same here...giving playback error....and freezes screen

**Comment by beastmaster-bit** [comment]
Refer to #277

**Comment by iMro0t** [comment]
Disable Extra channels from Settings. It's causing because of server issue from Jio

**Comment by Nzzyme** [comment]
> Seems fixed now.

It was fixed then but the issue is seen again. Followed this link and issue seems to be fixed

https://github.com/botallen/repository.botallen/issues/277

**Comment by elite-graphix** [comment]
Not Fixed at all since three days, not even a single channel is working without disabling extra hd channel, and also after disable extra channel sometime channel work but after some time giving playback error, kindly fix if you can, either jio change something on their server or something changed in PVR Extension after last update.
